name: Deploy Hugo Site to DigitalOcean

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.154.0'

      - name: Build Hugo site
        run: hugo --baseURL https://web1.bugelhartmann.dk/ --minify

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Sync site to DigitalOcean using rsync
        run: |
          SSH_USER="jetty"
          DO_DROPLET_IP="161.35.64.131"
          APP_NAME="web1"
          REMOTE_PATH="/home/jetty/deployment/site/$APP_NAME/"

          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./public/ $SSH_USER@$DO_DROPLET_IP:$REMOTE_PATH
